import { useState } from 'react';
import { generatePlainSummary } from '../services/api';

function PlainSummary({ paperId, paper }) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const result = await generatePlainSummary(paperId);
      setData(result);
    } catch (error) {
      console.error('Failed to generate summary:', error);
      alert(`Error: ${error.response?.data?.error || error.message || 'Failed to generate plain summary. Check console for details.'}`);
    } finally {
      setLoading(false);
    }
  };

  const generateShareCard = () => {
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${paper.title}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; background: #f3f4f6; }
    .card { background: white; border-radius: 12px; padding: 30px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
    h1 { color: #1f2937; margin-bottom: 10px; }
    .authors { color: #6b7280; margin-bottom: 20px; }
    .summary { line-height: 1.8; color: #374151; }
    .footer { margin-top: 30px; padding-top: 20px; border-top: 2px solid #e5e7eb; color: #9ca3af; font-size: 14px; }
  </style>
</head>
<body>
  <div class="card">
    <h1>${paper.title}</h1>
    <div class="authors">${paper.authors || 'Authors not available'}</div>
    <div class="summary">${data.summary.replace(/\n/g, '<br><br>')}</div>
    <div class="footer">
      Plain-language summary generated by Research Paper Visualization Platform
    </div>
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'paper-summary.html';
    link.click();
  };

  return (
    <div>
      {!data ? (
        <div className="text-center py-8">
          <p className="text-gray-600 mb-4">Generate a plain-language summary at 6th-grade reading level</p>
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="bg-blue-600 text-white px-6 py-2 rounded hover:bg-blue-700 disabled:bg-gray-300"
          >
            {loading ? 'Generating...' : 'Generate Plain Summary'}
          </button>
        </div>
      ) : (
        <div className="space-y-6">
          <div className="flex gap-2 mb-4">
            <button
              onClick={generateShareCard}
              className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 text-sm"
            >
              📤 Export Share Card
            </button>
            <button
              onClick={handleGenerate}
              className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 text-sm"
            >
              Regenerate
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h3 className="text-lg font-semibold mb-3 text-gray-900">Original Abstract</h3>
              <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
                <p className="text-sm text-gray-700 leading-relaxed">{data.original}</p>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold mb-3 text-blue-900">Plain-Language Summary</h3>
              <div className="bg-blue-50 p-4 rounded-lg border border-blue-200">
                <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-line">{data.summary}</p>
              </div>
            </div>
          </div>

          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
            <p className="text-sm text-yellow-800">
              <strong>Reading Level:</strong> 6th grade • <strong>Purpose:</strong> Make research accessible to general audiences
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

export default PlainSummary;
